<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Final Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>227e4001-258a-4207-99af-17acf1ccc4c4</testSuiteGuid>
   <testCaseLink>
      <guid>4661877f-f50a-4f47-86b3-98753c74a64a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST Create booking</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>30196b6f-636e-4cd6-8786-58b57f1b2fe1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST Create Multiple Booking</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7df40cda-4b47-489f-a3ac-16c03ead2062</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Booking multiple data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7df40cda-4b47-489f-a3ac-16c03ead2062</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>29b2d6b5-2106-4a2b-8d02-884b225c55c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7df40cda-4b47-489f-a3ac-16c03ead2062</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>c1142d30-aa74-4fa8-a27a-517f65f0a994</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37260e85-b8e0-448a-8912-6335b57484ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PUT Update Booking</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b76b5a8a-003f-47b1-af3f-1cd5cb77cb68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24d4af70-2a7e-43f3-b522-b1e8d0dc3ba2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8db50821-f45f-4083-938e-a876eed6d9ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ex 4- PATCH_DELETE Booking</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80fa00da-3ed6-42b0-8860-4f89cb163692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e32e1b5-9fdd-42a4-8471-6c4a84058f04</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
